### ISSUE TITLE
Can't restore the checkpoint, got shape mismatch errors

### ISSUE THREAD

**Issue by Xiaoxuan-Val** [MediaTek-NeuroPilot/mai22-real-time-video-sr#3]
Hi, thanks for this benchmark project! I intended to reload the pre-trained weight to validate the data but failed with loading the checkpoint.

I prepared data as instructed and was loading from 'snapshot/mobile_rrn_64/ckpt-150', and I got an error message as follows: 

(py3.7env) C:\Users\lixia\Desktop\mai22-real-time-video-sr>python run.py --process test --config_path config.yml
2022-07-22 12:08:12.891576: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-22 12:08:13.238556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9476 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:09:00.0, compute capability: 8.6
WARNING:tensorflow:From C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\autograph\impl\api.py:464: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

2022-07-22 12:08:21,982 [MAI VSR:INFO] learner.py:258: Restore from snapshot/mobile_rrn_64/ckpt-150
2022-07-22 12:08:21.992559: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "run.py", line 80, in <module>
    main(arguments)
  File "run.py", line 73, in main
    learner.test()
  File "C:\Users\lixia\Desktop\mai22-real-time-video-sr\learner\learner.py", line 266, in test
    pred_tensors = self.test_step(data_pair)
  File "C:\Users\lixia\Desktop\mai22-real-time-video-sr\learner\learner.py", line 177, in test_step
    pred_tensor, hidden_state = self.model([input_tensor, hidden_state], training=False)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "model/mobile_rrn.py", line 63, in call
    out = self.conv_first(x)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\keras\engine\base_layer.py", line 1030, in __call__
    self._maybe_build(inputs)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\keras\engine\base_layer.py", line 2659, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\keras\layers\convolutional.py", line 204, in build
    dtype=self.dtype)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\keras\engine\base_layer.py", line 663, in add_weight
    caching_device=caching_device)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\training\tracking\base.py", line 818, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\keras\engine\base_layer_utils.py", line 129, in make_variable
    shape=variable_shape if variable_shape else None)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\variables.py", line 266, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\variables.py", line 227, in _variable_v1_call
    shape=shape)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\variables.py", line 205, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2626, in default_variable_creator
    shape=shape)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\variables.py", line 270, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1613, in __init__
    distribute_strategy=distribute_strategy)
  File "C:\Users\lixia\anaconda3\envs\py3.7env\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1753, in _init_from_args
    (initial_value.shape, shape))
ValueError: The initial value's shape ((3, 3, 70, 64)) is not compatible with the explicitly supplied `shape` argument ((3, 3, 22, 16))

I was using python3.7, tensorflow2.6, and CUDA11.7.

Could you please indicate where the problem is? Thanks!

**Comment by XUSean0118** [comment]
You should modify self.base_channels in [model/mobile_rrn.py LN31](https://github.com/MediaTek-NeuroPilot/mai22-real-time-video-sr/blob/main/model/mobile_rrn.py#L31)  according to the checkpoint channel.

For example:
self.base_channels = 64 -> for  'snapshot/mobile_rrn_64/ckpt-150'
